language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

services: mysql

env: TRAVIS=1

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast-finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - travis_retry composer dump-autoload -o
  - mysql -e 'create database IF NOT EXISTS sprint;' -uroot
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - php -S localhost:8000 ./index.php &
  - sleep 3

script:
  - php index.php database quietMigrate
  - php codecept.phar run --env travis

after_failure:
  - cat tests/_output/*