language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services: mysql

env: TRAVIS=1

matrix:
  allow_failures:
    - php: hhvm
  fast-finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - travis_retry composer dump-autoload -o
  - mysql -e 'create database IF NOT EXISTS sprint;' -uroot
  - mysql -u root password 'root'

script:
  - php index.php database quietMigrate
  - php codecept.phar run

after_failure:
  - cat tests/_output/*